export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const SET_USER_STOCKS = "SET_USER_STOCKS";
export const SET_USER_BAL = "SET_USER_BAL";

export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const LOADING_GRAPH_DATA = "LOADING_GRAPH_DATA";
export const LOADED_GRAPH_DATA = "LOADED_GRAPH_DATA";
export const GRAPH_DATA_ERROR = "GRAPH_DATA_ERROR";
export const CHANGE_TICKER = "CHANGE_TICKER";
export const RETURN_GRAPH_TYPE = "RETURN_GRAPH_TYPE";
export const RETURN_GRAPH_PERIOD = "RETURN_GRAPH_PERIOD";
export const GRAPH_ERROR = "GRAPH_ERROR";
export const CLEAR_SEARCH_ERROR = "CLEAR_SEARCH_ERROR";

export const TRADE_SUCCESS = "TRADE_SUCCESS";
export const TRADE_ERROR = "TRADE_ERROR";
export const CLEAR_TRADE_ERROR = "CLEAR_TRADE_ERROR";
export const SET_TRADE_MSG = "SET_TRADE_MSG";
export const SET_ESTIMATED_PRICE = "SET_ESTIMATED_PRICE";


export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";