export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS ="LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const LOADING_GRAPH_DATA = "LOADING_GRAPH_DATA";
export const LOADED_GRAPH_DATA = "LOADED_GRAPH_DATA";
export const GRAPH_DATA_ERROR = "GRAPH_DATA_ERROR";
export const CHANGE_TICKER = "CHANGE_TICKER"
export const RETURN_GRAPH_TYPE = 'RETURN_GRAPH_TYPE';
export const RETURN_GRAPH_PERIOD = 'RETURN_GRAPH_PERIOD';
export const GRAPH_ERROR = 'GRAPH_ERROR'
export const CLEAR_SEARCH_ERROR = 'CLEAR_SEARCH_ERROR';

export const PROCESSING_TRADE = 'PROCESSING_TRADE';
export const PROCESSED_TRADE = 'PROCESSED_TRADE';